- name: Allow HASS Through Firewalld
  ansible.posix.firewalld:
    rich_rule: rule family="ipv4" source address="{{ groups['Caddy'][0] }}" port port="80" protocol="tcp" accept
    zone: public
    permanent: yes
    immediate: yes
    state: enabled
  register: firewalld
  when: groups['Caddy'] is defined and (groups['Caddy'] | length > 0)

- name: Reload Firewalld
  systemd:
    name: firewalld
    state: reloaded
  when: firewalld.changed
