- name: Install Httpd
  ansible.builtin.dnf:
    state: present
    name:
    - httpd

- name: Remove Default site
  ansible.builtin.file:
    path: /etc/httpd/conf.d/welcome.conf
    state: absent

- name: Enable HTTPd Service
  ansible.builtin.service:
    name: httpd
    state: started
    enabled: yes

- name: Add NextCloud Config to HTTPd
  vars:
    ServerName: "{{ hostname }}.{{ host_public_domain }}"
  ansible.builtin.template:
    src: ./templates/nextcloud_httpd_config.j2
    dest: /etc/httpd/conf.d/nextcloud.conf
